name: CI

on:
  push
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          build.bat
